spring:
  datasource:
    url: jdbc:postgresql://72.167.48.185:5433/dash-user-service
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: javatodev-internet-banking
      clientId: internet-banking-api-client
      client-secret: R7hdjxIQPOtPgY7eMNg3KVW9f2QFcQf4
  feign:
    client:
      core-banking: core-banking-service
